; TAC Instructions - Generated by STCC1
; Total instructions: 9

[   1] t1 = 5 add 3
[   2] v1 = t1
[   3] t2 = v1 gt 0
[   4] if_false t2 goto L1
[   5] param 42
[   6] t3 = call v100
[   7] L1:
[   8] goto L2
[   9] L2:
